# Generated by Django 3.2.13 on 2022-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_tocken', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('bg', 'Bulgarian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish')], default='English', max_length=100)),
                ('model', models.CharField(choices=[('en_core_web_lg', "spaCy's English Large"), ('gpt-j', 'GPT-J'), ('fast-gpt-j', 'Fast GPT-J'), ('fr_core_news_lg', "spaCy's French Large")], default='English', max_length=100)),
                ('use_gpu', models.BooleanField()),
                ('inpt_string', models.TextField()),
            ],
        ),
    ]
