# Generated by Django 3.2.13 on 2022-04-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='choices',
            name='model',
            field=models.CharField(choices=[('en_core_web_lg', "spaCy's English Large"), ('gpt-j', 'GPT-J'), ('fast-gpt-j', 'Fast GPT-J'), ('fr_core_news_lg', "spaCy's French Large"), ('bart-large-cnn', 'Bart-Large-CNN'), ('roberta-base-squad2', 'Roberta Base Squad 2')], default='English', max_length=100),
        ),
    ]
