# Generated by Django 3.2.13 on 2022-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20220422_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='inpt_string',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='choices',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('bg', 'Bulgarian'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish')], default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='choices',
            name='model',
            field=models.CharField(choices=[('en_core_web_lg', "spaCy's English Large"), ('gpt-j', 'GPT-J'), ('fast-gpt-j', 'Fast GPT-J'), ('fr_core_news_lg', "spaCy's French Large"), ('bart-large-cnn', 'Bart-Large-CNN'), ('roberta-base-squad2', 'Roberta Base Squad 2')], default='Bart-Large-CNN', max_length=100),
        ),
    ]
