# Generated by Django 3.2.13 on 2022-04-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220422_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='use_gpu',
            field=models.BooleanField(null=True),
        ),
    ]
