# Generated by Django 3.2.13 on 2022-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_choices_use_gpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='use_gpu',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
